version: '3'

volumes:
    shared_data:

services:
  head_node:
    build:
      context: .
      dockerfile: Dockerfile.head
    ports:
      - "9000:9000"
    environment:
      - "WESTPA_ZMQ_PORT=9000"
      - "WEST_SIM_ROOT=/data"
      - "HDF5_USE_FILE_LOCKING=FALSE"
    command: /app/entrypoint-head.sh
    volumes:
      - /home/jd/research/chatgpt_westpa/shared_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - head_node
    image: test-worker
    environment:
      - "WEST_SIM_ROOT=/data"
      - "MASTER_ADDRESS=head_node:9000"
      - "HDF5_USE_FILE_LOCKING=FALSE"
      - "MAMBA_ROOT_PREFIX=/opt/conda"
      - "PATH=/opt/conda/bin:${PATH}"
    command: /app/entrypoint-worker.sh
    volumes:
      - /home/jd/research/chatgpt_westpa/shared_data:/data
    tty: true
