FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libzmq3-dev \
        zlib1g-dev \
        git

ADD SynD /synd

RUN pip install --no-cache-dir \
        westpa \
        pyzmq \
        git+https://github.com/jdrusso/synd@parallel_fix

WORKDIR /data

COPY entrypoint-worker.sh /app/entrypoint-worker.sh

RUN chmod +x /app/entrypoint-worker.sh

#COPY west.cfg /west.cfg

ENTRYPOINT ["/app/entrypoint-worker.sh"]
