FROM mambaorg/micromamba:1.3.1

RUN micromamba install --yes --name base --channel conda-forge openmm==7.5.1 westpa pyzmq

WORKDIR /data

COPY entrypoint-worker.sh /app/entrypoint-worker.sh

USER root
RUN chmod +x /app/entrypoint-worker.sh
USER $MAMBA_USER

ENTRYPOINT ["/app/entrypoint-worker.sh"]
